export const initialState = {
  projects: {
    data: [
      {
        id: '1',
        category: 'UX, UI, coding',
        description: 'description-1',
        about: 'xxxx',
        image: '/images/01.JPG',
      },
      // {
      //   id: '2',
      //   category: 'UX, UI, coding',
      //   description: 'description-2',
      //   about: 'xxxx',
      //   image: '/images/Pantone_Store.JPG',
      // },
      // {
      //   id: '3',
      //   category: 'Presentation',
      //   description: 'description-3',
      //   about: 'xxxx',
      //   image: '/images/Layouts_presentation.JPG',
      // },
      // {
      //   id: '4',
      //   category: 'category-4',
      //   description: 'description-4',
      //   about: 'xxxx',
      //   image: '/images/Wordpress_jewelry.JPG',
      // },
      // {
      //   id: '5',
      //   category: 'category-5',
      //   description: 'description-5',
      //   about: 'xxxx',
      //   image: '/images/TwojRobot_Game.JPG',
      // },
      // {
      //   id: '6',
      //   category: 'category-6',
      //   description: 'description-6',
      //   about: 'xxxx',
      //   image: '/images/Posters.JPG',
      // },
      // {
      //   id: '7',
      //   category: 'category-7',
      //   description: 'description-7',
      //   about: 'xxxx',
      //   image: '/images/Graphics_Museum.JPG',
      // },
      // {
      //   id: '8',
      //   category: 'category-8',
      //   description: 'description-8',
      //   about: 'xxxx',
      //   image: '/images/Social_posts.JPG',
      // },
      // {
      //   id: '9',
      //   category: 'category-9',
      //   description: 'description-9',
      //   about: 'xxxx',
      //   image: '/images/Paper_Rock_Scissors.JPG',
      // },
      // {
      //   id: '10',
      //   category: 'category-10',
      //   description: 'description-10',
      //   about: 'xxxx',
      //   image: '/images/Layout_Fitness.JPG',
      // },
      // {
      //   id: '11',
      //   category: 'category-11',
      //   description: 'description-11',
      //   about: 'xxxx',
      //   image: '/images/Drawings.JPG',
      // },
      // {
      //   id: '12',
      //   category: 'category-12',
      //   description: 'description-12',
      //   about: 'xxxx',
      //   image: '/images/Architecture_Housing.JPG',
      // },
      // {
      //   id: '13',
      //   category: 'category-13',
      //   description: 'description-13',
      //   about: 'xxxx',
      //   image: '/images/Picture_Fake.JPG',
      // },
      // {
      //   id: '14',
      //   category: 'category-14',
      //   description: 'description-14',
      //   about: 'xxxx',
      //   image: '/images/Wordpress_Fitness.JPG',
      // },
      // {
      //   id: '15',
      //   category: 'category-15',
      //   description: 'description-15',
      //   about: 'xxxx',
      //   image: '/images/Notebook.JPG',
      // },
      // {
      //   id: '16',
      //   category: 'DTP',
      //   description: 'description-16',
      //   about: 'xxxx',
      //   image: '/images/DTP_Press.JPG',
      // },
      // {
      //   id: '17',
      //   category: 'category-17',
      //   description: 'description-17',
      //   about: 'xxxx',
      //   image: '/images/Branding_Coding.JPG',
      // },
      // {
      //   id: '18',
      //   category: 'category-18',
      //   description: 'description-18',
      //   about: 'xxxx',
      //   image: '/images/Shirts.JPG',
      // },
      // {
      //   id: '19',
      //   category: 'category-19',
      //   description: 'description-19',
      // about: 'xxxx',
      //   image: '/images/Newsletter.JPG',
      // },
      // {
      //   id: '20',
      //   category: 'category-20',
      //   description: 'description-20',
      // about: 'xxxx',
      //   image: '/images/Banners.JPG',
      // },
      // {
      //   id: '21',
      //   category: 'category-21',
      //   description: 'description-21',
      // about: 'xxxx',
      //   image: '/images/Architecture_Museum.JPG',

      // },
      // {
      //   id: '21',
      //   category: 'category-21',
      //   description: 'description-21',
      // about: 'xxxx',
      //   image: '/images/Interior_Store.JPG',
      // },
    ],
  },
};

