export const initialState = {
  projects: {
    data: [
      {
        id: '1',
        category: 'Web design',
        description: 'HTML, CSS, Photoshop',
        about: 'Conceptual web designs helped me to develop HTML and CSS skills. Skills that let me create forms along with complementary functions.',
        image: '/images/layouts.jpg',
      },
      {
        id: '2',
        category: 'Online store',
        description: 'React JS, Illustrator',
        about: 'Conceptutal design of Pantone colors online store. The project was made as a part of a web-development bootcamp. It consisted of many stages - from clear UI design up to final store mechanism made with React JavaScript library.',
        image: '/images/pantones.jpg',
      },
      {  
        id: '3',
        category: 'Data presentation',
        description: 'Photoshop, PPT',
        about: 'Well designed presentation makes complex data clear and informative. Regardless if it is made for an internal meeting or external client like NIKE’s managers my slides are eye catching and easily understandable by the audience.',
        image: '/images/presentation.jpg',
      },
      {
        id: '4',
        category: 'Web design',
        description: 'Wordpress, Photoshop',
        about: 'Handmade jewelry has as many forms as pieces that are made. This site was developed for a craftsman willing to present his wide range of products in a way that corresponded with his artistic soul.',
        image: '/images/jewelry.jpg',
      },
      {
        id: '5',
        category: 'Board game',
        description: 'Illustrator, Photoshop',
        about: 'Owning a company is a tough challenge. In TwojRobot despite being a busy franchisee I used my creativity and graphic skills to keep kids entertained and focused.',
        image: '/images/game.jpg',
      },
      {
        id: '6',
        category: 'Posters',
        description: 'Photoshop',
        about: 'While studying at the Polish Japanese Academy of Information Technology I learned that traditional art and computer technology can merge into surprising forms. These posters made from black and red threads symbolize three Shakespearian plays.',
        image: '/images/posters.jpg',
      },
      {
        id: '7',
        category: 'Museum map',
        description: 'Illustrator, Photoshop',
        about: 'Using a map is a skill on its own but designing a map that is understandable at first glance requires a great dose of empathy.',
        image: '/images/map.jpg',
      },
      {
        id: '8',
        category: 'Social posts',
        description: 'Illustrator, Photoshop, After Effects',
        about: 'Social media reach a great number of clients but rarely for more than a fraction of a second. Simple graphics and short animations when designed well, can deliver required message in a glimpse of an eye or draw users\' attention for longer.',
        image: '/images/posts.jpg',
      },
      {
        id: '9',
        category: 'Online game',
        description: 'HTML, CSS, JavaScript',
        about: 'To stay in the game you need to know new technologies. With JavaScript I can programme logic and actions for web elements just like in the case of the Rock, Paper, Scissors, Paper game.',
        image: '/images/scissors.jpg',
      },
      {
        id: '10',
        category: 'Web design',
        description: 'Illustrator',
        about: 'Not everyone likes to experiment when it comes to business. This layout was a brave concept that eventualy made its way onto the web.',
        image: '/images/magnum.jpg',
      },
      {
        id: '11',
        category: 'Drawings',
        description: 'Pencil',
        about: 'Pen and a piece of paper can make my day. While digital technology is creeping into every aspect of our lives these two things let me sit back and relax in an analogue way.',
        image: '/images/drawings.jpg',
      },
      {
        id: '12',
        category: 'Architecutral design',
        description: 'AutoCad, 3ds Max, Photoshop, Illustrator',
        about: 'Earning architecture degree at Warsaw Univeristy of Technology can be stresfull. Using skills and knowledge afterwards, while working with real designs, is definitely more fun!',
        image: '/images/housing.jpg',
      },
      {
        id: '13',
        category: 'Collage',
        description: 'Pen',
        about: 'Stickers and tags are garbage no more. I combine them into collages that hang on the wall proudly and represent real art.',
        image: '/images/picture.jpg',
      },
      {
        id: '14',
        category: 'Web design',
        description: 'CMS, Wordpress, Photoshop',
        about: 'Nowadays websites are products that are also used by a non-developers. This Wordpress blog was made for a client who could easily edit it whenever and wherever she wanted.',
        image: '/images/fitness.jpg',
      },
      {
        id: '15',
        category: 'Drawings',
        description: 'Pen',
        about: 'For some, pen is an oldschool tool but I use it everyday and I use it a lot. Whether for work or for fun it helps me to get my thoughts together.',
        image: '/images/notebook.jpg',
      },
      {
        id: '16',
        category: 'Typesetting',
        description: 'InDesign, Illustrator',
        about: 'Typesetting and DTP are crucial while converting digital forms into printable versions. I create graphics and forms that can be sent directly to a printing house.',
        image: '/images/dtp.jpg',
      },
      {
        id: '17',
        category: 'Branding',
        description: 'Illustrator',
        about: 'Logotypes are fun to make. Combining multiple meanings into simple form can be a real jigsaw.',
        image: '/images/branding.jpg',
      },
      // {
      //   id: '18',
      //   category: 'Branding',
      //   description: 'Illustrator',
      //   about: 'If Snowboard wasn\'t invented why would we need winter? As an active member of sport association during my collage days I was responsible for providing the graphic content for all sorts of gadgets.',
      //   image: '/images/shirts.jpg',
      // },
      {
        id: '18',
        category: 'Young Media Lions Competition',
        description: 'Strategy, Photoshop, Illustrator',
        about: 'Strategy for promoting the day without complaining was one of the stages of the national competition called Young Media Lions. Out of 38 two-person teams, we turned out to be the best in Poland. This victory let us represent our country on the international level and participate in jubilee 60th Cannes Lions Festival of Creativity. Seven-day adventure in France proved to me how crucial is cooperation of various industries. Since then I am fascinated with joining art with technology.',
        image: '/images/yml.jpg',
      },
      // {
      //   id: '19',
      //   category: 'category-19',
      //   description: 'description-19',
      // about: 'xxxx',
      //   image: '/images/newsletter.jpg',
      // },
      // {
      //   id: '20',
      //   category: 'category-20',
      //   description: 'description-20',
      // about: 'xxxx',
      //   image: '/images/banners.jpg',
      // },
      // {
      //   id: '21',
      //   category: 'category-21',
      //   description: 'description-21',
      // about: 'xxxx',
      //   image: '/images/museum.jpg',

      // },
      // {
      //   id: '21',
      //   category: 'category-21',
      //   description: 'description-21',
      // about: 'xxxx',
      //   image: '/images/interior.jpg',
      // },
    ],
  },
};

